### ISSUE TITLE
Step Model Broken

### ISSUE THREAD

**Issue by toedtling** [Duet3D/Duet3-Mainboard-6HC#1]
Hi!

The Step Modell is broken. It seems to be an Export Issue. Could anybody upload it again? I cant import it in Fusion 360 and Solidworks

**Comment by T3P3** [comment]
I downloaded the file as a test and it opens in FreeCad. I don't have Fusion360 or Solidworks to test.

**Comment by grndkntrl** [comment]
It opens without problems for me in Fusion 360 on Win7 x64.
